//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo_Just4Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigInfo
    {
        public string ConfigName { get; set; }
        public int SlotId { get; set; }
        public string ConfigPayload { get; set; }
        public string Desc { get; set; }
        public string Owner { get; set; }
        public bool IsActive { get; set; }
        public int SubmitIntervalHours { get; set; }
        public System.DateTime CreateDtm { get; set; }
        public System.DateTime ModifiedDtm { get; set; }
        public string InterfaceConfigPayload { get; set; }
        public int JobType { get; set; }
        public long Id { get; set; }
    }
}
