//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo_Just4Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilePublishStrategy
    {
        public string StrategyName { get; set; }
        public int PartitionCount { get; set; }
        public string TargetModelFilePattern { get; set; }
        public string TargetRootPathSi { get; set; }
        public string TargetRootPathXLite { get; set; }
        public string TargetRootPathProd { get; set; }
        public string Description { get; set; }
        public string Tag { get; set; }
        public int ModelTarget { get; set; }
        public System.DateTime CreateDtm { get; set; }
        public System.DateTime ModifiedDtm { get; set; }
        public long Id { get; set; }
    }
}
