//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo_Just4Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilePublishInfo
    {
        public int Status { get; set; }
        public int SlotId { get; set; }
        public int PartitionCount { get; set; }
        public string ModelFilePattern { get; set; }
        public string CheckSumFilePattern { get; set; }
        public string Tag { get; set; }
        public int ModelTarget { get; set; }
        public int TargetEnv { get; set; }
        public string SourceExperimentId { get; set; }
        public string Description { get; set; }
        public System.DateTime TrainingEndTime { get; set; }
        public string PublishRecord { get; set; }
        public string Owner { get; set; }
        public bool IsManualPublish { get; set; }
        public System.DateTime CreateDtm { get; set; }
        public System.DateTime ModifiedDtm { get; set; }
        public string FilePublishStrategyName { get; set; }
        public long Id { get; set; }
    }
}
