//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo_Just4Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobInfo
    {
        public int Status { get; set; }
        public int SlotId { get; set; }
        public string ExperimentId { get; set; }
        public string JobDesc { get; set; }
        public string Tag { get; set; }
        public System.DateTime TrainingEndTime { get; set; }
        public string Config { get; set; }
        public string PublishRecord { get; set; }
        public string SubmitService { get; set; }
        public int JobType { get; set; }
        public string Owner { get; set; }
        public int RetryTime { get; set; }
        public System.DateTime CreateDtm { get; set; }
        public System.DateTime ModifiedDtm { get; set; }
        public string InterfaceConfig { get; set; }
        public string ValidationRecord { get; set; }
        public int OperationType { get; set; }
        public long LineCount { get; set; }
        public long Impressions { get; set; }
        public double Ctr { get; set; }
        public long MaxFeatureId { get; set; }
        public long Id { get; set; }
    }
}
