//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo_Just4Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricsInfo
    {
        public long JobId { get; set; }
        public string Slice { get; set; }
        public long Impression { get; set; }
        public long Click { get; set; }
        public double CTR { get; set; }
        public double AUC { get; set; }
        public double PRAUC { get; set; }
        public double LogLoss { get; set; }
        public double RIG { get; set; }
        public double PredictionError { get; set; }
        public double AvgPclick { get; set; }
        public System.DateTime CreatedDtm { get; set; }
        public System.DateTime ModifiedDtm { get; set; }
        public string ValidationDataName { get; set; }
        public string ValidationDataPath { get; set; }
        public long Id { get; set; }
    }
}
