//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo_Just4Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitorInfo
    {
        public int Status { get; set; }
        public string Config { get; set; }
        public string SubmitService { get; set; }
        public string ServiceHost { get; set; }
        public string MonitorType { get; set; }
        public string Owner { get; set; }
        public string ReportMailBody { get; set; }
        public System.DateTime ReportDate { get; set; }
        public System.DateTime CreatedDtm { get; set; }
        public System.DateTime ModifiedDtm { get; set; }
        public long Id { get; set; }
    }
}
