//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo_Just4Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpsRecord
    {
        public string ExperimentId { get; set; }
        public int SlotId { get; set; }
        public int OperationType { get; set; }
        public string UserName { get; set; }
        public System.DateTime CreateDtm { get; set; }
        public System.DateTime ModifiedDtm { get; set; }
        public string OperationDetail { get; set; }
        public bool OperationResult { get; set; }
        public long Id { get; set; }
    }
}
