//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo_Just4Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int Status { get; set; }
        public string UserAlias { get; set; }
        public string UserDomain { get; set; }
        public int UserRole { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDtm { get; set; }
        public System.DateTime ModifiedDtm { get; set; }
        public long Id { get; set; }
    }
}
