//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo_DbFirstDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Essay
    {
        public long id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Title2 { get; set; }
    }
}
