//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo_DbFirstDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlotMemory
    {
        public string AD_tag { get; set; }
        public int Version { get; set; }
        public string TotalSize { get; set; }
        public string CPSize { get; set; }
        public System.DateTime CreatedTime { get; set; }
    }
}
