//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo_ModelFirstdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompactModel
    {
        public long ModelId { get; set; }
        public string ModelPath { get; set; }
        public short SlotId { get; set; }
        public short FormatVersion { get; set; }
        public Nullable<long> PipelineId { get; set; }
        public Nullable<System.DateTime> TrainingEndTimeUTC { get; set; }
        public Nullable<long> MaxFeatureId { get; set; }
        public Nullable<long> ModelSize { get; set; }
        public Nullable<long> CRC32C { get; set; }
        public string Md5sum { get; set; }
        public Nullable<bool> IsProd { get; set; }
        public System.DateTime CreatedDtim { get; set; }
        public System.DateTime ModifiedDtim { get; set; }
        public Nullable<short> EncodedSlotId { get; set; }
        public string Owner { get; set; }
        public string Description { get; set; }
        public string SlotName { get; set; }
        public string Tag { get; set; }
    }
}
