//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo_ModelFirstdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public long FlightId { get; set; }
        public string FlightName { get; set; }
        public string FlightOwner { get; set; }
        public string FlightPara1 { get; set; }
        public string FlightPara3 { get; set; }
    }
}
