//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo_ModelFirstdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightRanker
    {
        public long FlightId { get; set; }
        public string RankerName { get; set; }
        public short AbacusClassifierId { get; set; }
        public System.DateTime CreatedDtim { get; set; }
        public System.DateTime ModifiedDtim { get; set; }
    }
}
