//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo_ModelFirstdemo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WoodblockModelKPIsEntities : DbContext
    {
        public WoodblockModelKPIsEntities()
            : base("name=WoodblockModelKPIsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompactModel> CompactModels { get; set; }
        public virtual DbSet<FlightRanker> FlightRankers { get; set; }
        public virtual DbSet<Flight> Flights { get; set; }
        public virtual DbSet<RankerModel> RankerModels { get; set; }
        public virtual DbSet<Ranker> Rankers { get; set; }
        public virtual DbSet<UsageCheckHistory> UsageCheckHistories { get; set; }
    }
}
