//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo_ModelFirstdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankerModel
    {
        public long RankerId { get; set; }
        public short SlotId { get; set; }
        public short FormatVersion { get; set; }
        public string WBConfig { get; set; }
        public Nullable<long> WBCRC32C { get; set; }
        public System.DateTime CreatedDtim { get; set; }
        public System.DateTime ModifiedDtim { get; set; }
    }
}
