//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo_ModelFirstdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slot
    {
        public long SlotId { get; set; }
        public string SlotName { get; set; }
        public string SlotOwner { get; set; }
        public string FlightUsage { get; set; }
        public string RankerUsage { get; set; }
    }
}
