//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo_ModelFirstdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsageCheckHistory
    {
        public long Id { get; set; }
        public System.DateTime CreatedDtim { get; set; }
        public System.DateTime ModifiedDtim { get; set; }
        public bool IsSuccess { get; set; }
        public string Message { get; set; }
        public bool IsSendAlarm { get; set; }
    }
}
